cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name="checkout"),
    path('update_cart/<int:product_id>/<slug:action>/', views.update_cart, name="update_cart"),

    path('hx_menu_cart/', views.hx_menu_cart, name="hx_menu_cart"),
    path('hx_summary/', views.hx_summary, name="hx_summary"),
]

nordichomes/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace="core")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('products/', include("products.urls", namespace="products")),
    path('orders/', include("orders.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path("start_order/", views.start_order, name="start_order"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .cart import Cart
from products.models import Product


def add_to_cart(request, product_id):
    cart = Cart(request)
    product_id_str = str(product_id)
    
    if product_id_str in cart.cart and cart.cart[product_id_str]['quantity'] >= 1:
        cart.add(product_id, update_quantity=True)
    else:
        cart.add(product_id)

    return render(request, 'cart/menu_cart.html')


def cart(request):
    return render(request, 'cart/cart.html', {
        'title' : 'Cart overview',
        'next_page': reverse('cart:checkout'),
    })


def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == 'item_increment':
        cart.add(product_id, update_quantity=True)
    elif action == 'item_decrement':
        cart.add(product_id, quantity=-1, update_quantity=True)

    product = get_object_or_404(Product, id=product_id)

    try:
        quantity = cart.cart[str(product_id)]['quantity']
    except:
        response = HttpResponse('')
        response['HX-Trigger'] = 'update-menu-cart'
        return response

    item = {
        'product': product,
        'total_price': quantity * product.price,
        'quantity': quantity,
    }

    response = render(request, 'cart/partials/cart_item.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-cart'

    return response


@login_required()
def checkout(request):
    return render(request, "cart/checkout.html", {
        'title' : 'Checkout',
    })


def hx_menu_cart(request):
    return render(request, 'cart/menu_cart.html')

def hx_summary(request):
    return render(request, 'cart/partials/summary.html', {'next_page': reverse('cart:checkout')})
    

cart/templates/cart/cart.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">
    {% for item in cart %}
        {% include 'cart/partials/cart_item.html' %}
    {% endfor %}
    
    <div hx-get="{% url 'cart:hx_summary' %}" hx-trigger="update-menu-cart from:body" hx-swap="outerHTML" hx-target=".summary"></div>
    {% include 'cart/partials/summary.html' %}

</div>
{% endblock %}

cart/templates/cart/checkout.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<form method="post" action="{% url 'orders:start_order' %}">
    {% csrf_token %}
    
    <div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">
        <div class="product w-full lg:w-3/4">

            <h1 class="mb-5 text-3xl">Checkout</h1>

            <div class="w-full pr-6">
                <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Shipping information</h2>
                    <div class="flex space-x-6">

                        <div class="w-1/2 mb-4">
                            <label for="first_name" class="inline-block mb-2">First name</label>
                            <input type="text" id="first_name" name="first_name" class="w-full p-5 rounded-xl" value="{{ request.user.first_name }}">
                            
                            {% if form %}
                            {% if form.first_name.errors %}
                            <div class="w-full p-5 mt-2 bg-red-200 text-red-800 rounded-xl">
                                {% for error in form.first_name.errors %}
                                <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% endif %}
                        </div>

                        <div class="w-1/2 mb-4">
                            <label for="last_name" class="inline-block mb-2">Last name</label>
                            <input type="text" id="last_name" name="last_name" class="w-full p-5 rounded-xl" value="{{ request.user.last_name }}">

                            {% if form %}
                            {% if form.last_name.errors %}
                            <div class="w-full p-5 mt-2 bg-red-200 text-red-800 rounded-xl">
                                {% for error in form.last_name.errors %}
                                <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% endif %}
                        </div>

                    </div>

                    <div class="mb-4">
                        <label for="address" class="inline-block mb-2">Address</label>
                        <input type="text" id="address" name="address" class="w-full p-5 rounded-xl">
                    
                        {% if form %}
                        {% if form.address.errors %}
                        <div class="w-full p-5 mt-2 bg-red-200 text-red-800 rounded-xl">
                            {% for error in form.address.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                    
                    <div class="flex space-x-6">
                        <div class="w-1/2 mb-4">
                            <label for="zipcode" class="inline-block mb-2">Zip code</label>
                            <input type="text" id="zipcode" name="zipcode" class="w-full p-5 rounded-xl">

                            {% if form %}
                            {% if form.zipcode.errors %}
                            <div class="w-full p-5 mt-2 bg-red-200 text-red-800 rounded-xl">
                                {% for error in form.zipcode.errors %}
                                <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% endif %}
                        </div>

                        <div class="w-1/2 mb-4">
                            <label for="city" class="inline-block mb-2">City</label>
                            <input type="text" id="city" name="city" class="w-full p-5 rounded-xl">

                            {% if form %}
                            {% if form.city.errors %}
                            <div class="w-full p-5 mt-2 bg-red-200 text-red-800 rounded-xl">
                                {% for error in form.city.errors %}
                                <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% endif %}
                        </div>

                    </div>
                </div>
                <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Contact information</h2>
                    
                    <div class="mb-4">
                        <label for="email" class="inline-block mb-2">Email</label>
                        <input type="email" id="email" name="email" class="w-full p-5 rounded-xl" value="{{ request.user.email }}">
                    
                        {% if form %}
                        {% if form.email.errors %}
                        <div class="w-full p-5 mt-2 bg-red-200 text-red-800 rounded-xl">
                            {% for error in form.email.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                    
                    <div class="mb-4">
                        <label for="phone" class="inline-block mb-2">Phone</label>
                        <input type="tel" id="phone" name="phone" class="w-full p-5 rounded-xl">

                        {% if form %}
                        {% if form.phone.errors %}
                        <div class="w-full p-5 mt-2 bg-red-200 text-red-800 rounded-xl">
                            {% for error in form.phone.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Payment information</h2>
                </div>
            </div>
        </div>
        {% include 'cart/partials/summary.html' %}
    </div>
</form> 
{% endblock %}

cart/templates/cart/menu_cart.html
<a href="{% url 'cart:cart' %}" id="menu-cart-button" class="inline-block relative w-5 h-5">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
    <div class="w-5 h-5 absolute flex justify-center items-center -top-3 left-5 bg-indigo-500 text-white text-xs font-medium rounded-full">{{ cart|length }}</div>
</a>