cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name="checkout"),
    path('update_cart/<int:product_id>/<slug:action>/', views.update_cart, name="update_cart"),

    path('hx_menu_cart/', views.hx_menu_cart, name="hx_menu_cart"),
    path('hx_summary/', views.hx_summary, name="hx_summary"),
]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name="home"),
    path('shop/', views.shop, name="shop"),
    path('signup/', views.signup_user, name="signup_user"),
    path('login/', views.LoginUser.as_view(), name="login_user"),
    path('logout/', LogoutView.as_view(), name="logout_user"),
    path('myaccount/', views.myaccount, name="my_account"),
    path('myaccount/edit/', views.edit_account, name="edit_account"),
    path('payment/success/', views.success, name="success"),
]

nordichomes/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace="core")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('products/', include("products.urls", namespace="products")),
    path('orders/', include("orders.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products.views import product_detail

app_name = "products"

urlpatterns = [
    path('<slug:slug>', product_detail, name="product_detail"),
]

core/forms.py
from django import forms 
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from django.core.exceptions import ValidationError


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=50, label="First name", required=True, 
        widget=forms.TextInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )
    last_name = forms.CharField(
        max_length=50, label="Last name", required=True, 
        widget=forms.TextInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )
    username = forms.CharField(
        max_length=50, label="Username", required=True, 
        widget=forms.TextInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )
    email = forms.EmailField(
        max_length=255, label="Email", required=True, 
        widget=forms.TextInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )
    password1 = forms.CharField(
        max_length=255, label="Password", required=True, 
        widget=forms.PasswordInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )
    password2 = forms.CharField(
        max_length=255, label="Repeat password", required=True, 
        widget=forms.PasswordInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match")


class LogInForm(forms.Form):
    username = forms.CharField(
        max_length=50, label="Username", required=True, 
        widget=forms.TextInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )
    password = forms.CharField(
        max_length=255, label="Password", required=True, 
        widget=forms.PasswordInput(attrs={"class":"w-full mt-2 py-4 px-6 bg-white rounded-xl"})
    )

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)
    
    def clean(self):
        cd = self.cleaned_data
        username = cd.get('username')
        passwd = cd.get('password')

        user = authenticate(self.request, username=username, password=passwd)
        if user == None:
            raise ValidationError("invalid username or password")
        
        self.user = user

    def get_user(self):
        return self.user

class AccountForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'username': 'Username',
            'email': 'Email',
            'first_name': 'First name',
            'last_name': 'Last name',
        }


class EditAccountForm(AccountForm):
    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)

        if self.instance:
            self.fields['first_name'].widget.attrs['placeholder'] = self.instance.first_name or 'Enter your first name'
            self.fields['email'].widget.attrs['placeholder'] = self.instance.email or 'Enter your email'
            self.fields['last_name'].widget.attrs['placeholder'] = self.instance.last_name or 'Enter your last name'


    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'inline-block w-80 mt-2 py-2 px-4 bg-white border border-gray-300 rounded-md'}),
            'email': forms.TextInput(attrs={'class': 'inline-block w-80 mt-2 py-2 px-4 bg-white border border-gray-300 rounded-md'}),
            'first_name': forms.TextInput(attrs={'class': 'inline-block w-80 mt-2 py-2 px-4 bg-white border border-gray-300 rounded-md'}),
            'last_name': forms.TextInput(attrs={'class': 'inline-block w-80 mt-2 py-2 px-4 bg-white border border-gray-300 rounded-md'}),
        }

core/views.py
import stripe

from django.conf import settings
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.views.decorators.http import require_http_methods

from products.models import Product, Category

from .forms import SignUpForm, LogInForm, EditAccountForm, AccountForm


def home(request):
    products = Product.objects.all()[:8]

    return render(request, "core/home.html", {
        'products': products,
        'title': 'Home'
    })


def shop(request):
    active_category = request.GET.get('category', '')
    query = request.GET.get('query', '')

    categories = Category.objects.all() 

    if active_category:
        products = Product.objects.filter(category__slug=active_category)
    else:
        products = Product.objects.all()
    
    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))


    context = {
        'title': 'Shopping',
        'products': products,
        'categories': categories,
        'active_category': active_category,
    }        

    return render(request, "core/shop.html", context)
        

def signup_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, "core/signup.html", {
        "form": form, 
        "title": 'Sign up',
    })


class LoginUser(LoginView):
    template_name = "core/login.html"
    authentication_form = LogInForm
    extra_context = {
        'title': 'Log in',
    }


@require_http_methods(['GET'])
@login_required
def myaccount(request):
    form = AccountForm(instance=request.user)
    
    return render(request, 'core/myaccount.html', {'form': form})


@require_http_methods(['GET', 'POST'])
@login_required
def edit_account(request):
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)

        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            return redirect('core:my_account')
    else:
        form = EditAccountForm(instance=request.user)

    return render(request, 'core/edit_account.html', {'form': form})


def success(request):
    return render(request, "core/success.html")

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Nordic Homes</title>
    <link rel="icon" href="{% static 'images/favicon-32x32.png' %}" type="image/x-icon" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="border border-gray-300">
        <div class="max-w-6xl mx-auto py-2 px-6 xl:px-0 flex items-center justify-between">
            <div class="flex tems-center space-x-6">
                <a href="/" class="py-4 text-lg text-purple-500 font-semibold">Nordic Homes</a>

                <ul class="flex items-center sm:space-x-4">
                    <li class="hidden sm:inline-block"><a href="{% url 'core:shop' %}">Shop</a></li>
                    <li class="hidden sm:inline-block"><a href="#">About</a></li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <form method="post" action="{% url 'core:logout_user' %}">
                            {% csrf_token %}
                            <button type="submit">Log out</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'core:login_user' %}">Log in</a><span class="text-purple-500"> | </span><a href="{% url 'core:signup_user' %}">Sign up</a></li>
                    {% endif %}
                    
                </ul>
            </div>

            <div class="flex items-center space-x-4 mr-4">
                <a href="{% url 'core:my_account' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                    </svg>
                </a>

                <div
                    hx-get="{% url 'cart:hx_menu_cart' %}"
                    hx-trigger="update-menu-cart from:body"
                    hx-swap="innerHTML"
                >
                    {% include 'cart/menu_cart.html' %}
                </div>
            </div>
        </div>
    </nav>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-gray-100">
        <div class="max-w-6xl mx-auto py-10 px-6 xl:px-0 md:flex justify-between">
            <div class="mb-12 md:mb-0">
                <h2 class="mb-5 uppercase texg-lg">About us</h2>

                <p class="text-gray-700">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore, mollitia temporibus </p>
            </div>
                
            <div>            
                <h2 class="mb-5 uppercase texg-lg">Social links</h2>

                <ul class="space-y-2">
                    <li href="#" class="text-purple-800">Facebook</li>
                    <li href="#" class="text-purple-800">Twitter</li>
                    <li href="#" class="text-purple-800">Instagram</li>
                </ul>
            <div>
        </div>
    </footer>

    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

core/templates/core/edit_account.html
{% extends 'core/base.html' %}

{% block title %}Edit account{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto p-6 xl:px-0">
    <h1 class="mb-5 text-3xl">Edit account</h1>

    <form class="space-y-3" method="post" action="{% url 'core:edit_account' %}" autocomplete="off">
        {% csrf_token %}

        {% for f in form %}
        <label for="{{ f.id_for_label }}" class="inline-block w-32">{{ f.label }}: </label>{{ f }}
        <br>

        {% if f.errors %}
        <div class="w-[28rem] py-2 px-4 bg-red-200 text-red-800 rounded-md">
            {% for error in f.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}

        {% endfor %}

        {% if form.non_field_errors %}
        <div class="w-[28rem] py-2 px-4 bg-red-200 text-red-800 rounded-md">
            <ul>
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        <button type="submit" class="inline-block mt-5 py-2 px-4 rounded-md bg-purple-500 hover:bg-purple-700 text-white">Save</a>
    </form>
</div>
{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<header class="px-6 py-10 lg:py-20 bg-purple-500">
    <div class="max-w-3xl mx-auto text-center">
        <p class="mb-2 text-3xl lg:text-5xl text-white">Welcome to Nordic Homes</p>
        <p class="mb-10 text-white ">We sell furniture for modern homes</p>

        <a href="{% url 'core:shop' %}" class="inline-block px-8 py-4 rounded-xl bg-white text-purple-500 hover:bg-gray-200">Start shopping</a>
    </div>
</header>

<div class="max-w-6xl mx-auto py-2 px-6 xl:px-0">
    <div class="flex items-start flex-wrap">
        {% for product in products %}
            {% include 'products/partials/product_list_item.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="max-w-lg mx-auto flex flex-wrap p-6">
    <div class="w-full bg-gray-100 p-6 rounded-xl">
        <h1 class="mb-6 text-2xl font-medium">Log in</h1>

        <form method="post" autocomplete="off" action="." class="space-y-3">
            {% csrf_token %}

            {% for f in form %}
            <div>
                <label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
            </div>

            {% if f.errors %}
            <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                {% for error in f.errors %}
                <p>{{ error }}</p>
                {% endfor %}
            </div>
            {% endif %}

            {% endfor %}


            {% if form.non_field_errors %}
            <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                <ul>
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div>
                <button type="submit" class="py-4 px-6 rounded-xl text-white bg-purple-500 hover:bg-purple-700 font-medium">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/myaccount.html
{% extends 'core/base.html' %}

{% block title %}My account{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto p-6 xl:px-0">
    <h1 class="mb-5 text-3xl">My account</h1>
    <form class="mb-8 space-y-3">
        {% for f in form %}
        <div>
            <strong class="inline-block w-32">{{ f.label }}</strong>
            <span>{{ f.value }}</span>
        </div>
        {% endfor %}

        <a href="{% url 'core:edit_account' %}" class="inline-block py-2 px-4 rounded-md bg-purple-500 hover:bg-purple-700 text-white">Edit</a>
    </form>

    <hr>

    <h2 class="text-3xl my-6">My orders</h2>

    <div class="w-full text-right mb-6 p-6 flex flex-wrap rounded-xl bg-gray-100">
        {% for order in request.user.orders.all %}
        <div class="w-full mb-6 text-xl text-left"><a href="#">Order id: {{ order.id }}</a></div>
        <div class="w-full">
            {% for item in order.items.all %}
            <div class="product flex mb-6">
                <div class="w-1/4">
                    {% if item.product.image %}
                    <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="hover:shadow-lg rounded-xl">
                    {% else %}
                    <img src="{{ item.product.get_thumbnail }}" alt="{{ item.product.name }}" class="hover:shadow-lg rounded-xl">
                    {% endif %}
                </div>
                <div class="w-3/4 pl-6">
                    <div class="flex justify-between mb-6">
                        <a href="{% url 'products:product_detail' item.product.slug %}" class="text-lg text-left truncate w-44 sm:w-64 lg:w-[30rem]">{{ item.product.name }}</a>
                        <span class="text-gray-500">${{ item.product.price }}</span>
                    </div>

                    <hr>
                    
                    <ul class="mt-5">
                        <li>Quantity: {{ item.quantity }}</li>
                    </ul>
                </div>
            </div>

            {% endfor %}
        </div>
        
        <div class="block w-full mb-4">
            <div class="ml-auto p-4 space-y-2 text-left text-md inline-block bg-white rounded-md">
                <div class="w-40 flex justify-between">
                    <span class="font-medium">Total:</span>
                    <div>
                        <span class="text-purple-700 font-medium">$</span>
                        <span>{{ order.get_total_price }}</span>
                    </div>
                </div>
                <div class="w-40 flex justify-between">
                    <span class="font-medium">Date:</span>
                    <span>{{ order.created_at|date:"d.m.Y" }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/shop.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap item-start py-6 px-6 xl:px-0">
    <div class="w-full lg:w-1/4 sm:flex sm:items-center lg:block">
        
        <form method="get" action="." class="w-full sm:w-3/4 lg:w-full">
            <h3 class="mb-3 text-xl uppercase">Search</h3>
            <div class="flex focus-within:outline focus-within:outline-2 focus-within:outline-purple-500 rounded-sm">
                <input type="text" name="query" class="p-4 w-full bg-gray-100 border-0 outline-none focus:outline-none" placeholder="Search...">
                
                <button class="flex items-center justify-center bg-gray-100 border-0 w-20">
                    <svg class="size-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
                    </svg>
                </button>
            </div>
        </form>

        <div class="sm:w-1/4 lg:w-full sm:pl-8 lg:pl-0">
            <h3 class="mt-6 mb-3 text-xl uppercase sm:text-right lg:text-left">Categories</h3>
            <ul class="space-y-2 sm:text-right lg:text-left">
                <li><a href="{% url 'core:shop' %}" class="{% if not active_category %}text-purple-500{% else %}text-gray-500{% endif %}">All categories</a></li>
                {% for category in categories %}
                <li><a href="{% url 'core:shop' %}?category={{ category.slug }}" class="{% if category.slug == active_category %}text-purple-500{% else %}text-gray-500{% endif %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="w-full lg:w-3/4 flex flex-wrap justify-center md:justify-normal">
        {% for product in products %}
            <div class="w-4/5 md:w-1/3 xl:w-1/4 py-6 px-2 lg:p-6">
                {% if product.image %}
                <a href="{% url 'products:product_detail' product.slug %}">
                    <img class="hidden md:inline-block rounded-xl hover:shadow-lg object-cover w-full aspect-square" src="{{ product.get_thumbnail }}" alt="{{ product.slug }}">
                </a>
                <a href="{% url 'products:product_detail' product.slug %}">
                    <img class="md:hidden rounded-xl hover:shadow-lg object-cover w-full aspect-square" src="{{ product.image.url }}" alt="{{ product.slug }}">
                </a>
                {% else %}
                <a href="{% url 'products:product_detail' product.slug %}">
                    <img class="rounded-xl hover:shadow-lg object-cover w-full aspect-square" src="{{ product.get_thumbnail }}" alt="{{ product.slug }}">
                </a>
                {% endif %}
                                
                <div class="pt-3 flex items-start justify-between">
                    <a href="{% url 'products:product_detail' product.slug %}">{{ product.name|truncatewords:6 }}</a>
                    <a
                        hx-get="{% url 'cart:add_to_cart' product.id %}"
                        hx-target="#menu-cart-button"
                        hx-swap="outerHTML"
                        class="text-purple-500 hover:text-purple-800 cursor-pointer"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
                        </svg>
                    </a>
                </div>
                <p class="pt-1 text-gray-400">${{ product.price }}</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="max-w-lg mx-auto flex flex-wrap p-6">
    <div class="w-full bg-gray-100 p-6 rounded-xl">
        <h1 class="mb-6 text-2xl font-medium">Sign up</h1>

        <form method="post" autocomplete="off" action="." class="space-y-3">
            {% csrf_token %}

            {% for f in form %}
            <div>
                <label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
            </div>

            {% if f.errors %}
            <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                {% for error in f.errors %}
                <p>{{ error }}</p>
                {% endfor %}
            </div>
            {% endif %}

            {% endfor %}


            {% if form.non_field_errors %}
            <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                <ul>
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div>
                <button type="submit" class="py-4 px-6 rounded-xl text-white bg-purple-500 hover:bg-purple-700 font-medium">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/success.html
{% extends 'core/base.html' %}

{% block title %}Success{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto py-6 px-6 xl:px-0">
    <h1 class="mb-5 text-3xl font-medium">Your purcase was successful!</h1>

    <div class="space-y-4 mb-4">
        <p>Thank you for choosing us!</p>
        <p>You can go back to home page using this <a class="text-purple-700 hover:text-purple-800" href="{% url 'core:home' %}">link</a></p>
    </div>
</div>
{% endblock %}