cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name="checkout"),
    path('update_cart/<int:product_id>/<slug:action>/', views.update_cart, name="update_cart"),

    path('hx_menu_cart/', views.hx_menu_cart, name="hx_menu_cart"),
    path('hx_summary/', views.hx_summary, name="hx_summary"),
]

nordichomes/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace="core")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('products/', include("products.urls", namespace="products")),
    path('orders/', include("orders.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products.views import product_detail

app_name = "products"

urlpatterns = [
    path('<slug:slug>', product_detail, name="product_detail"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .cart import Cart
from products.models import Product


def add_to_cart(request, product_id):
    cart = Cart(request)
    product_id_str = str(product_id)
    
    if product_id_str in cart.cart and cart.cart[product_id_str]['quantity'] >= 1:
        cart.add(product_id, update_quantity=True)
    else:
        cart.add(product_id)

    return render(request, 'cart/menu_cart.html')


def cart(request):
    return render(request, 'cart/cart.html', {
        'title' : 'Cart overview',
        'next_page': reverse('cart:checkout'),
    })


def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == 'item_increment':
        cart.add(product_id, update_quantity=True)
    elif action == 'item_decrement':
        cart.add(product_id, quantity=-1, update_quantity=True)

    product = get_object_or_404(Product, id=product_id)

    try:
        quantity = cart.cart[str(product_id)]['quantity']
    except:
        response = HttpResponse('')
        response['HX-Trigger'] = 'update-menu-cart'
        return response

    item = {
        'product': product,
        'total_price': quantity * product.price,
        'quantity': quantity,
    }

    response = render(request, 'cart/partials/cart_item.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-cart'

    return response


@login_required()
def checkout(request):
    return render(request, "cart/checkout.html", {
        'title' : 'Checkout',
    })


def hx_menu_cart(request):
    return render(request, 'cart/menu_cart.html')

def hx_summary(request):
    return render(request, 'cart/partials/summary.html', {'next_page': reverse('cart:checkout')})
    

cart/templates/cart/partials/cart_item.html
<div class="product w-full lg:w-3/4 lg:pr-5" id="cart-item-{{ item.product.id }}">
    <div class="product mb-4 sm:mb-6 flex">
        <a href="{% url 'products:product_detail' item.product.slug %}" class="w-1/4 min-w-[7rem]">
            <img src="{{ item.product.get_thumbnail }}" alt="{{ item.product.name }}" class="hover:shadow-lg rounded-xl">
        </a>
        <div class="w-3/4 pl-4 sm:pl-6 text-right">
            <div class="flex justify-between text-md sm:text-lg">
                <a href="{% url 'products:product_detail' item.product.slug %}" class="text-left truncate w-[10rem] sm:w-64 lg:w-full">{{ item.product.name|truncatewords:6 }}</a>
                <span class="mb-6 pl-2 text-gray-500">${{ item.total_price }}</span>
            </div>
            <hr>
            <div class="inline-block">
                <div class="mt-6 flex items-center space-x-4">
                    <a
                        class="p-3 bg-gray-100 cursor-pointer"
                        hx-get="{% url 'cart:update_cart' item.product.id 'item_decrement' %}"
                        hx-target="#cart-item-{{ item.product.id }}"
                        hx-swap="outerHTML"
                    >-</a>
                    
                    <span>{{ item.quantity }}</span>
                    
                    <a 
                        class="p-3 bg-gray-100 cursor-pointer"
                        hx-get="{% url 'cart:update_cart' item.product.id 'item_increment' %}"
                        hx-target="#cart-item-{{ item.product.id }}"
                        hx-swap="outerHTML"
                    >+</a>
                </div>
            </div>
        </div>
    </div>
</div>

cart/templates/cart/partials/summary.html
{% for item in cart %}
{% endfor %}
<div class="summary w-full lg:w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
    <h2 class="uppercase text-lg mb-5">Summary</h2>
    <div class="mb-6 flex justify-between text-md sm:text-lg">
        <span class="font-semibold">Total</span>
        <span>${{ cart.get_total_cost }}</span>
    </div>
    {% if next_page %}
    <a href="{{ next_page }}" class="inline-block px-6 py-3 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Checkout</a>
    {% else %}
    <button type="submit" class="inline-block px-6 py-3 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Create order</button>
    {% endif %}
</div>